### ISSUE TITLE
《An Empirical Evaluation of In-Memory Multi-Version Concurrency Control》论文翻译 的几处小typo

### ISSUE THREAD

**Issue by IcePigZDB** [MrCroxx/mrcroxx.github.io.bk#7]
在阅读中发现了几处小typo, 顺手提一下，都可以直接搜到:

> 我们描述了MVCC DBMS的4中核心并发控制协议

4中 -> 4种

> 当事务视图读取或更新一个被其它事务持有其写入锁的版本时，DBMS会打断该事务。

视图 -> 试图

> 而在内存式DBMS中，分开存储时不必要的，

时 -> 是

> master版本时元组的当前版本

时 -> 是

> 这时大多数MVCC DBMS中通用的方法

时 -> 是

> 我们队YCSB[14] Benchmark进行了修改

队 -> 对

> 我摩恩在Peloton中做了最后一个实验

摩恩 -> 们

> 因为该策略需要DBMS讲每个新版本插入到所有的辅助索引中，这会使更新操作变得更慢。

讲 -> 将

> DNMS需要为每个epoch追踪

DNMS -> DBMS

**Comment by MrCroxx** [comment]
Thanks a lot! I'll fix them after hours.
